### ISSUE TITLE
Use of "Dragons" mods without permission

### ISSUE THREAD

**Issue by aaay-aaay** [Dual-Iron/RainyBepis#1]
Dragons.dll, Dragons.HookGenCompatibility.dll and Dragons.PublicDragon.dll are all mods made by me. I have not (from a copyright perspective or a moral one) given you permission to distribute them like this (or at all) - please remove them. If this can't work without them, then, well... maybe you should have asked me first.

._.

**Comment by aaay-aaay** [comment]
I probably should have made this more clear: I'm "bee" in the discord.

**Comment by Dual-Iron** [comment]
Linked the original and removed the copy. Didn't even cross my mind, this was my bad. Thanks for contacting me!
